server:
  port: 8084
spring:
  application:
    name: service-sleuth
eureka:
  client:
    service-url:
       defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true



logging:
  level:
    root: INFO
    org.springframework.cloud.sleuth: DEBUG
