server:
  port: 9098
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: service-auth
  redis:
    host: a.thoughts-go.top
    password: rj20170103P@ss!2#4%6
    database: 0
    port: 26379

