spring:
  application:
    name: ui1
eureka:
  client:
    service-url:
       defaultZone: http://admin:admin@localhost:8761/eureka/
server:
  port: 8000
security:
  oauth2:
    resource:
      jwt:
        key-uri: http://localhost:9096/oauth/token_key
    client:
      client-id: client_2
      client-secret: 123456
      access-token-uri: http://localhost:9096/oauth/token
      grant-type: password
      scope: server
      user-authorization-uri: http://localhost:9096/oauth/authorize
