server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        #native:
          #search-locations:
          #- classpath: D:\\microservice3\\config\\
  #cloud:
    #config:
      #server:
        git:
          #uri: https://github.com/ddssssdd/ms-config.git
          uri: http://47.95.5.250:3000/pls/common-config.git
          username: config_user
          password: 12345678



#http://www.itmuch.com/spring-cloud/finchley-19/
eureka:
  client:
    service-url:
       defaultZone: http://admin:admin@localhost:8761/eureka/eureka/
encrypt:
  key: foo